name = "my-portfolio"
compatibility_date = "2024-09-13"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".vercel/output/static"
not_found_handling = "single-page-application"

[vars]
NODE_VERSION = "18.18.0"