name = "my-portfolio"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js"

[assets]
directory = ".vercel/output/static"
not_found_handling = "single-page-application"

[vars]
NODE_VERSION = "18.18.0"